export const aircraft = [
  { id: "a380",        name: "A380",          category: "airliner", value: 10 },
  { id: "an225",       name: "An-225",        category: "cargo",    value: 10 },

  { id: "b747",        name: "Boeing 747",    category: "airliner", value: 9 },
  { id: "b747cargo",   name: "747 Cargo",     category: "cargo",    value: 9 },

  { id: "b777",        name: "Boeing 777",    category: "airliner", value: 8 },
  { id: "b777cargo",   name: "777F",          category: "cargo",    value: 8 },
  { id: "a350",        name: "A350",          category: "airliner", value: 8 },
  { id: "c17",         name: "C-17",          category: "military", value: 8, modern: true },
  { id: "sr71",        name: "SR-71",         category: "military", value: 8, modern: false },
  { id: "vulcan",      name: "Vulcan",        category: "military", value: 8, modern: false },

  { id: "b787",        name: "Boeing 787",    category: "airliner", value: 8 },
  { id: "a340",        name: "A340",          category: "airliner", value: 8 },
  { id: "kc46",        name: "KC-46",         category: "military", value: 8, modern: true },
  { id: "kc130j",      name: "KC-130J",       category: "military", value: 8, modern: true },

  { id: "b767",        name: "Boeing 767",    category: "airliner", value: 7 },
  { id: "b767cargo",   name: "767F",          category: "cargo",    value: 7 },
  { id: "a330",        name: "A330",          category: "airliner", value: 7 },
  { id: "a330cargo",   name: "A330F",         category: "cargo",    value: 7 },
  { id: "a330mrtt",    name: "A330 MRTT",     category: "military", value: 7, modern: true },
  { id: "md11",        name: "MD-11",         category: "airliner", value: 7 },
  { id: "md11f",       name: "MD-11F",        category: "cargo",    value: 7 },
  { id: "b29",         name: "B-29",          category: "military", value: 7, modern: false },
  { id: "e3",          name: "E-3",           category: "military", value: 7, modern: true },
  { id: "p8",          name: "P-8",           category: "military", value: 7, modern: true },

  { id: "b757",        name: "Boeing 757",    category: "airliner", value: 6 },
  { id: "b757cargo",   name: "757F",          category: "cargo",    value: 6 },
  { id: "c130",        name: "C-130",         category: "military", value: 6, modern: false },
  { id: "c130hercules",name: "C-130 Hercules",category: "military", value: 6, modern: false },

  { id: "b727",        name: "Boeing 727",    category: "airliner", value: 5 },
  { id: "b727cargo",   name: "727F",          category: "cargo",    value: 5 },
  { id: "b707",        name: "Boeing 707",    category: "airliner", value: 5 },
  { id: "kc707",       name: "KC-707",        category: "military", value: 5, modern: false },
  { id: "f4phantom",   name: "F-4 Phantom",   category: "military", value: 5, modern: false },
  { id: "f18",         name: "F/A-18",        category: "military", value: 5, modern: true },
  { id: "a10",         name: "A-10",          category: "military", value: 5, modern: true },
  { id: "su27",        name: "Su-27",         category: "military", value: 5, modern: true },

  { id: "eurofighter", name: "Eurofighter",   category: "military", value: 6, modern: true },

  { id: "a320",        name: "A320",          category: "airliner", value: 4 },
  { id: "b737",        name: "Boeing 737",    category: "airliner", value: 4 },
  { id: "b737cargo",   name: "737F",          category: "cargo",    value: 4 },
  { id: "a220",        name: "A220",          category: "airliner", value: 4 },
  { id: "e190",        name: "E190",          category: "airliner", value: 4 },
  { id: "crj700",      name: "CRJ-700",       category: "airliner", value: 4 },
  { id: "q400",        name: "Q400",          category: "airliner", value: 4 },
  { id: "atr72",       name: "ATR 72",        category: "airliner", value: 4 },
  { id: "atr72f",      name: "ATR 72F",       category: "cargo",    value: 4 },
  { id: "dc10",        name: "DC-10",         category: "airliner", value: 7 },
  { id: "dc10f",       name: "DC-10F",        category: "cargo",    value: 7 },
  { id: "md90",        name: "MD-90",         category: "airliner", value: 4 },
  { id: "comet",       name: "Comet",         category: "airliner", value: 4 },
  { id: "tristar",     name: "Tristar",       category: "airliner", value: 7 },
  { id: "concorde",    name: "Concorde",      category: "airliner", value: 7 },

  { id: "learjet",     name: "Learjet",       category: "ga",       value: 3 },
  { id: "kingair260",  name: "King Air 260",  category: "ga",       value: 2 },
  { id: "c182",        name: "Cessna 182",    category: "ga",       value: 2 },
  { id: "c182floats",  name: "C182 Floats",   category: "seaplane", value: 2 },
  { id: "c402",        name: "Cessna 402",    category: "ga",       value: 2 },
  { id: "sf50",        name: "SF50",          category: "ga",       value: 2 },
  { id: "da50",        name: "DA50",          category: "ga",       value: 2 },

  { id: "c172",        name: "Cessna 172",    category: "ga",       value: 1 },
  { id: "c172floats",  name: "C172 Floats",   category: "seaplane", value: 1 },
  { id: "piperCub",    name: "Piper Cub",     category: "ga",       value: 1 },
  { id: "piperCubFloats", name: "Piper Cub Floats", category: "seaplane", value: 1 },
  { id: "twinotter",   name: "Twin Otter",    category: "ga",       value: 2 },
  { id: "twinotterFloats", name: "Twin Otter Floats", category: "seaplane", value: 2 },
  { id: "caravan",     name: "Caravan",       category: "ga",       value: 2 },
  { id: "caravanFloats", name: "Caravan Floats", category: "seaplane", value: 2 },
  { id: "caravanCargo", name: "Caravan Cargo", category: "cargo",   value: 2 },

  { id: "seaplane",    name: "Generic Seaplane", category: "seaplane", value: 2 },
  { id: "heli",        name: "Generic Helicopter", category: "heli", value: 1 },

  { id: "p51",         name: "P-51",          category: "military", value: 3, modern: false },
  { id: "p38",         name: "P-38",          category: "military", value: 3, modern: false },
  { id: "corsair",     name: "Corsair",       category: "military", value: 3, modern: false },
  { id: "hurricane",   name: "Hurricane",     category: "military", value: 3, modern: false },
  { id: "zero",        name: "Zero",          category: "military", value: 3, modern: false },
  { id: "mig15",       name: "Mig-15",        category: "military", value: 3, modern: false },

  { id: "f14",         name: "F-14",          category: "military", value: 6, modern: true },
  { id: "f15e",        name: "F-15E",         category: "military", value: 6, modern: true },
  { id: "f16",         name: "F-16",          category: "military", value: 5, modern: true },
  { id: "f22",         name: "F-22",          category: "military", value: 7, modern: true },
  { id: "f35b",        name: "F-35B",         category: "military", value: 7, modern: true },
  { id: "su57",        name: "Su-57",         category: "military", value: 7, modern: true },
  { id: "hawkT1",      name: "Hawk T1",       category: "military", value: 4, modern: false },

  { id: "s92",         name: "S-92",          category: "heli",     value: 2 },
  { id: "bell412",     name: "Bell 412",      category: "heli",     value: 1 },
  { id: "uh60",        name: "UH-60",         category: "heli",     value: 2 }
];
